### ISSUE TITLE
Ingredient Type Dropdown: Add New Ingredient Type

### ISSUE THREAD

**Issue by PistolRcks** [PistolRcks/recipe-app#7]
As a cook, if an ingredient type is not listed, I would like to write in my own for increased customization.

Confirmation:
The dropdown for selecting ingredient types should have a text box to enter a currently non-existent ingredient type.

**Comment by dvcky** [comment]
Live demo accessible @ `https://*********************/sep/team8/Cole/ingredient.php`

If this looks like it covers what we need, let me know and I'll close both this and #9.

**Comment by PistolRcks** [comment]
Looks good. Should also fulfill #9. We'll close this during the meeting today.

**Comment by PistolRcks** [comment]
Closed as part of scrum today.
